<?php

# Some labels
$module[$modulename]["title"]   = "Administraci&#243;n de phpShop";
$module_menu            	= "$modulename/html/menu.ihtml";
$menu_label 			= "Men&#250; Administrativo";

// User List
$user_list_mnu			= "Listar Usuarios";
$user_list_lbl			= "Lista de Usuarios";
$user_list_username		= "Nombre C&#243;digo";
$user_list_full_name		= "Nombre Entero";
$user_list_group		= "Grupo";

// User Form
$user_form_mnu			= "A&#241;adir Usuario";
$user_form_lbl			= "Informaci&#243;n del Usuario";
$user_form_billto_lbl		= "Direcci&#243;n de Cobro";
$user_form_address_info_lbl     = "Informaci&#243;n de Transporte";
$user_form_shipto_lbl		= "Direcci&#243;n de Transporte";
$user_form_add_shipto_lbl	= "A&#241;adir Direcci&#243;n";
$user_form_address_label	= "Apodo para Direcci&#243;n";
$user_form_first_name		= "Primer Nombre";
$user_form_last_name		= "Apellido";
$user_form_middle_name		= "Segundo Nombre";
$user_form_title		= "T&#237;tulo";
$user_form_username		= "Nombre C&#243;digo";
$user_form_password_1		= "Contrase&#241;a";
$user_form_password_2		= "Confirme Contrase&#241;a";
$user_form_perms		= "Permiso";
$user_form_company_name		= "Nombre de Compa&#241;&#237;a";
$user_form_address_1		= "Direcci&#243;n 1";
$user_form_address_2		= "Direcci&#243;n 2";
$user_form_city			= "Ciudad";
$user_form_state		= "Estado";
$user_form_zip			= "C&#243;digo Postal";
$user_form_country		= "Pa&#237;s";
$user_form_phone		= "Tel&#233;fono";
$user_form_fax			= "Fax";
$user_form_email		= "Correo Electr&#243;nico";

// Module List
$module_list_mnu		= "Listar M&#243;dulos";
$module_list_lbl		= "Lista de M&#243;dulos";
$module_list_name		= "Nombre";
$module_list_perms		= "Permisos";
$module_list_functions		= "Funciones";
$module_list_order		= "Orden";

// Module Form
$module_form_mnu		= "A&#241;adir M&#243;dulo";
$module_form_lbl		= "Informaci&#243;n del M&#243;dulo";
$module_form_name		= "Nombre del M&#243;dulo";
$module_form_perms		= "Permisos del M&#243;dulo";
$module_form_header		= "Cabeza del M&#243;dulo";
$module_form_footer		= "Pi&#233; del M&#243;dulo";
$module_form_menu		= "Lista en Menu?";
$module_form_order		= "Orden de Lista";
$module_form_description	= "Descripci&#243;n del M&#243;dulo";
$module_form_language_code	= "Lenguage: C&#243;digo";
$module_form_language_file	= "Archivo";
$module_form_module_label	= "Menu";

// Function List
$function_list_mnu		= "Listar Funciones";
$function_list_lbl		= "Lista de Funciones";
$function_list_name 		= "Nombre de la Funci&#243;n";
$function_list_class 		= "Nombre de la Clase";
$function_list_method 		= "Nombre del M&#233;todo";
$function_list_perms 		= "Permisos";

// Function Form
$function_form_mnu		= "Anadir Funci&#243;n";
$function_form_lbl		= "Informaci&#243;n de la Funci&#243;n";
$function_form_name		= "Nombre de la Funci&#243;n";
$function_form_class		= "Nombre de la Clase";
$function_form_method		= "Nombre del M&#233;todo";
$function_form_perms		= "Permisos";
$function_form_description	= "Descripci&#243;n";

?>
