<?php

# Some labels
$module[$modulename]["title"]   	= "Administraci&#243;n de Productos";
$module_menu            		= "$modulename/html/menu.ihtml";
$menu_label 				= "Men&#250; Productos";

$product_current_lbl			= "Producto Actual";
$item_current_lbl			= "Art&#237;culo Actual";

// Product List
$product_list_mnu			= "Listar Productos";
$product_list_lbl			= "Lista de Productos";
$product_list_name			= "Nombre";
$product_list_sku			= "SKU";
$product_list_category       = "Categoria";
$product_list_publish			= "Publicar";

// Product Form
$product_form_mnu			= "A&#241;adir Producto";
$product_form_add_item_mnu		= "A&#241;adir Art&#237;culo";
$product_form_add_another_item_mnu	= "A&#241;adir Otro Art&#237;culo";

$product_form_new_product_lbl		= "Producto Nuevo";
$product_form_update_product_lbl	= "Poner Producto al D&#237;a";
$product_form_product_info_lbl		= "Informaci&#243;n del Producto";
$product_form_product_status_lbl	= "Status del Producto";
$product_form_product_dim_weight_lbl	= "Dimensiones y Peso del Producto";
$product_form_product_images_lbl	= "Im&#225;genes del Producto";

$product_form_new_item_lbl		= "Art&#237;culo Nuevo";
$product_form_update_item_lbl 		= "Poner Art&#237;culo al D&#237;a";
$product_form_item_info_lbl		= "Informaci&#243;n del Art&#237;culo";
$product_form_item_status_lbl		= "Status del Art&#237;culo";
$product_form_item_dim_weight_lbl	= "Dimensiones y Peso del Art&#237;culo";
$product_form_item_images_lbl		= "Im&#225;genes del Art&#237;culo";
$product_form_return_lbl 		= "Regresar al Producto Pariente";
$product_form_image_delete_lbl		= "Escribir \"none\" para borrar Imagen.";
$product_form_product_items_lbl		= "Art&#237;culos del Producto";
$product_form_item_attributes_lbl	= "Atributos del Art&#237;culo";
$product_form_delete_product_msg	= "Seguro quiere borrar este Producto\\ny los Art&#237;culos relacionados a &#233;l";
$product_form_delete_item_msg		= "Seguro quiere borrar este Art&#237;culo";
$product_form_vendor			= "Distribuidor";
$product_form_sku			= "SKU";
$product_form_name			= "Nombre";
$product_form_url			= "URL";
$product_form_category			= "Categor&#237;a";
$product_form_price			= "Precio";
$product_form_description		= "Descripci&#243;n";
$product_form_s_desc			= "Descripci&#243;n Breve";
$product_form_in_stock			= "A la Mano";
$product_form_on_order			= "Ordenado";
$product_form_available_date		= "Fecha Disponibilidad";
$product_form_special			= "A la Venta";
$product_form_discount_type		= "Tipo de Descuento";
$product_form_publish			= "Publicar?";
$product_form_length			= "Largo";
$product_form_width			= "Ancho";
$product_form_height			= "Alto";
$product_form_dimension_uom		= "Unidades de Medir";
$product_form_weight			= "Peso";
$product_form_weight_uom		= "Unidades de Medir";
$product_form_thumb_image		= "Imagen Peque&#241;a";
$product_form_full_image		= "Imagen Grande";
$product_form_image_update_lbl		= "Cargar";

// Product Display
$product_display_add_product_lbl	= "Resultado de A&#241;adir Producto";
$product_display_update_product_lbl	= "Resultado de Poner al D&#237;a Producto";
$product_display_add_item_lbl		= "Resultado de A&#241;adir Art&#237;culo";
$product_display_update_item_lbl	= "Resultado de Poner al D&#237;a Art&#237;culo";

// Product Category List
$category_list_mnu			= "Listar Categor&#237;as";
$category_list_lbl			= "Arbol de Categor&#237;as";

// Product Category Form
$category_form_mnu			= "A&#241;adir Categor&#237;a";
$category_form_lbl			= "Informaci&#243;n de la Categor&#237;a";
$category_form_name			= "Nombre de la Categor&#237;a";
$category_form_parent			= "Pariente";
$category_form_description		= "Descripci&#243;n de la Categor&#237;a";
$category_form_publish			= "Publicar?";
$category_form_flypage			= "Pagina Principal";


// Product Attribute List
$attribute_list_mnu			= "Listar Atributos";
$attribute_list_lbl			= "Lista de Atributos para";
$attribute_list_name			= "Nombre";
$attribute_list_order			= "Orden en la Lista";

// Product Attribute Form
$attribute_form_mnu			= "A&#241;adir Atributo";
$attribute_form_lbl			= "Forma de Atributos";
$attribute_form_new_for_product		= "Nuevo Atributo para Producto";
$attribute_form_update_for_product	= "Poner al D&#237;a Atributo de Producto";
$attribute_form_new_for_item		= "Nuevo Atributo para Art&#237;culo";
$attribute_form_update_for_item		= "Poner al D&#237;a Atributo de Art&#237;culo";
$attribute_form_name			= "Nombre del Atributo";
$attribute_form_order			= "Orden en la Lista";


// Product Price List
$price_list_mnu				= "Listar Categor&#237;as";
$price_list_lbl				= "Arbol de Precios";
$price_list_for_lbl			= "Precios para";
$price_list_group_name			= "Nombre del Grupo";
$price_list_price			= "Precio";
$product_list_currency			= "Moneda";

// Product Price Form
$price_form_mnu				= "Precios";
$price_form_lbl				= "Informaci&#243;n de Precio";
$price_form_new_for_product		= "Nuevo Precio para Producto";
$price_form_update_for_product		= "Poner al D&#237;a Precio de Producto";
$price_form_new_for_item		= "Nuevo Precio para Art&#237;culo";
$price_form_update_for_item		= "Poner al D&#237;a Precio de Art&#237;culo";
$price_form_price			= "Precio";
$price_form_currency			= "Moneda";
$price_form_group			= "Grupo de Cliente";
$price_publish				= "Publicar?";
?>
