<?php

# Some labels
$module[$modulename]["title"]   = "Administraci&#243;n de Tienda";
$module_menu            	= "$modulename/html/menu.ihtml";
$menu_label 			= "Men&#250; Tienda";

// Store Form
$store_form_mnu			= "Tienda";
$store_form_lbl			= "Informaci&#243;n de Tienda";
$store_form_contact_lbl		= "Informaci&#243;n de Contacto";
$store_form_full_image		= "Im&#225;gen Grande";
$store_form_upload		= "Cargar Im&#225;gen";
$store_form_store_name		= "Nombre de la Tienda";
$store_form_company_name	= "Nombre de la Compa&#241;&#237;a";
$store_form_address_1		= "Direcci&#243;n 1";
$store_form_address_2		= "Direcci&#243;n 2";
$store_form_city		= "Ciudad";
$store_form_state		= "Estado";
$store_form_country		= "Pa&#237;s";
$store_form_zip			= "C&#243;digo Postal";
$store_form_phone		= "Tel&#233;fono";
$store_form_currency		= "Moneda";
$store_form_category		= "Categor&#237;a de Tienda";
$store_form_last_name		= "Apellido";
$store_form_first_name		= "Primer Nombre";
$store_form_middle_name		= "Segundo Nombre";
$store_form_title		= "T&#237;tulo";
$store_form_phone_1		= "Tel&#233;fono 1";
$store_form_phone_2		= "Tel&#233;fono 2";
$store_form_fax			= "Fax";
$store_form_email		= "Correo Electr&#243;nico";
$store_form_image_path		= "Path a la Im&#225;gen";
$store_form_description		= "Descripci&#243;n";

// User List
$user_list_mnu			= "Listar Usuarios";
$user_list_lbl			= "Lista de Usuarios";
$user_list_username		= "Nombre C&#243;digo";
$user_list_full_name		= "Nombre Entero";
$user_list_group		= "Grupo";

// User Form
$user_form_mnu			= "A&#241;adir Usuario";
$user_form_lbl			= "Informaci&#243;n del Usuario";
$user_form_billto_lbl		= "Direcci&#243;n de Cobro";
$user_form_address_info_lbl	= "Informaci&#243;n de Transporte";
$user_form_shipto_lbl		= "Direcci&#243;n de Transporte";
$user_form_add_shipto_lbl	= "A&#241;adir Direcci&#243;n";
$user_form_address_label	= "Apodo para Direcci&#243;n";
$user_form_first_name		= "Primer Nombre";
$user_form_last_name		= "Apellido";
$user_form_middle_name		= "Segundo Nombre";
$user_form_title		= "T&#237;tulo";
$user_form_username		= "Nombre C&#243;digo";
$user_form_password_1		= "Contrase&#241;a";
$user_form_password_2		= "Confirme Contrase&#241;a";
$user_form_perms		= "Permiso";
$user_form_company_name		= "Nombre de Compa&#241;&#237;a";
$user_form_address_1		= "Direcci&#243;n 1";
$user_form_address_2		= "Direcci&#243;n 2";
$user_form_city			= "Ciudad";
$user_form_state		= "Estado";
$user_form_zip			= "C&#243;digo Postal";
$user_form_country		= "Pa&#237;s";
$user_form_phone		= "Tel&#233;fono";
$user_form_fax			= "Fax";
$user_form_email		= "Correo Electr&#243;nico";

// Payment Method List
$payment_method_list_mnu        = "Listar Metodos de Pago";
$payment_method_list_lbl        = "Lista de Metodos";
$payment_method_list_name       = "Nombre";
$payment_method_list_code       = "Codigo";
$payment_method_list_discount   = "Descuento";
$payment_method_list_shopper_group      = "Grupo de Comprador";
$payment_method_list_enable_processor   = "Autorizar";

// Payment Method Form
$payment_method_form_mnu        = "Anadir Metodo de Pago";
$payment_method_form_lbl        = "Forma de Metodo de Pago";
$payment_method_form_name       = "Nombre del Metodo";
$payment_method_form_shopper_group = "Grupo de Comprador";
$payment_method_form_discount    = "Descuento";
$payment_method_form_code       = "Codigo";
$payment_method_form_list_order = "Orden de Lista";
$payment_method_form_enable_processor   = "Autorizar";

?>
