<?php

# Some labels
$module[$modulename]["title"]   = "Store Administration";
$module_menu            	= "$modulename/html/menu.ihtml";
$menu_label 			= "Store Menu";

// Store Form
$store_form_mnu			= "Edit Store";
$store_form_lbl			= "Store Information";
$store_form_contact_lbl		= "Contact Information";
$store_form_full_image		= "Full Image";
$store_form_upload		= "Upload Image";
$store_form_store_name		= "Store Store Name";
$store_form_company_name	= "Store Company Name";
$store_form_address_1		= "Address 1";
$store_form_address_2		= "Address 2";
$store_form_city		= "City";
$store_form_state		= "State/Region";
$store_form_country		= "Country";
$store_form_zip			= "Zip";
$store_form_phone		= "Phone";
$store_form_currency		= "Currency";
$store_form_category		= "Store Category";
$store_form_last_name		= "Last Name";
$store_form_first_name		= "First Name";
$store_form_middle_name		= "Middle Name";
$store_form_title		= "Title";
$store_form_phone_1		= "Phone 1";
$store_form_phone_2		= "Phone 2";
$store_form_fax			= "Fax";
$store_form_email		= "Email";
$store_form_image_path		= "Image Path";
$store_form_description		= "Description";

// User List
$user_list_mnu			= "List Users";
$user_list_lbl			= "User List";
$user_list_username		= "Username";
$user_list_full_name		= "Full Name";
$user_list_group		= "Group";

// User Form
$user_form_mnu			= "Add User";
$user_form_lbl			= "User Information";
$user_form_billto_lbl		= "Bill To Information";
$user_form_address_info_lbl	= "Address Information";
$user_form_shipto_lbl		= "Shipping Addresses";
$user_form_add_shipto_lbl	= "Add Address";
$user_form_address_label	= "Address Nickname";
$user_form_first_name		= "First Name";
$user_form_last_name		= "Last Name";
$user_form_middle_name		= "Middle Name";
$user_form_title		= "Title";
$user_form_username		= "Username";
$user_form_password_1		= "Password";
$user_form_password_2		= "Confirm Password";
$user_form_perms		= "Permissions";
$user_form_company_name		= "Company Name";
$user_form_address_1		= "Address 1";
$user_form_address_2		= "Address 2";
$user_form_city			= "City";
$user_form_state		= "State/Region";
$user_form_zip			= "Zip";
$user_form_country		= "Country";
$user_form_phone		= "Phone";
$user_form_fax			= "Fax";
$user_form_email		= "Email";


// Payment Method List
$payment_method_list_mnu        = "List Payment Methods";
$payment_method_list_lbl	= "Payment Method List";
$payment_method_list_name	= "Name";
$payment_method_list_code	= "Code";
$payment_method_list_discount	= "Discount";
$payment_method_list_shopper_group	= "Shopper Group";
$payment_method_list_enable_processor	= "Authorize";

// Payment Method Form
$payment_method_form_mnu        = "Add Payment Method";
$payment_method_form_lbl	= "Payment Method Form";
$payment_method_form_name	= "Payment Form Name";
$payment_method_form_shopper_group = "Shopper Group";
$payment_method_form_discount    = "Discount";
$payment_method_form_code       = "Code";
$payment_method_form_list_order	= "List Order";
$payment_method_form_enable_processor	= "Authorize";

// Basic Report
$navigation_title = "Report Administration";
$sale_title = "Sales Reporting";

/* labels for rpt_sales */
$rpt_sales_page_title = "Sales Activity Overview";

$interval_title = "Set Interval";
 $interval_monthly_title = "Monthly";
 $interval_weekly_title = "Weekly";
 $interval_daily_title = "Daily";

$thisMonth_button = "This Month";
$lastMonth_button = "Last Month";
$last60_button = "Last 60 days";
$last90_button = "Last 90 days";

$start_date_title = "Start on";
$end_date_title = "End at";

?>


