<?php

# Some labels
$module[$modulename]["title"]   = "Administraci&#243;n de Clientes";
$module_menu            	= "$modulename/html/menu.ihtml";
$menu_label 			= "Men&#250; Clientes";


// Shopper List
$shopper_list_mnu		= "Listar Clientes";
$shopper_list_lbl		= "Lista de Clientes";
$shopper_list_username		= "Nombre C&#243;digo";
$shopper_list_name		= "Nombre Entero";
$shopper_list_group		= "Grupo";

// Shopper Form
$shopper_form_mnu		= "A&#241;adir Clientes";
$shopper_form_lbl		= "Informaci&#243;n de Clientes";
$shopper_form_billto_lbl	= "Direcci&#243;n de Cobro";
$shopper_form_address_info_lbl	= "Informaci&#243;n de Transporte";
$shopper_form_shipto_lbl	= "Direcci&#243;n de Transporte";
$shopper_form_add_shipto_lbl	= "A&#241;adir Direcci&#243;n";
$shopper_form_address_label	= "Apodo para Direcci&#243;n";
$shopper_form_username		= "Nombre C&#243;digo";
$shopper_form_first_name	= "Primer Nombre";
$shopper_form_last_name		= "Apellido";
$shopper_form_middle_name	= "Segundo Nombre";
$shopper_form_title		= "T&#237;tulo";
$shopper_form_shoppername	= "Nombre C&#243;digo";
$shopper_form_password_1	= "Contrase&#241;a";
$shopper_form_password_2	= "Confirme Contrase&#241;a";
$shopper_form_group		= "Grupo";
$shopper_form_company_name	= "Nombre de Compa&#241;&#237;a";
$shopper_form_address_1		= "Direcci&#243;n 1";
$shopper_form_address_2		= "Direcci&#243;n 2";
$shopper_form_city		= "Ciudad";
$shopper_form_state		= "Estado";
$shopper_form_zip		= "C&#243;digo Postal";
$shopper_form_country		= "Pa&#237;s";
$shopper_form_phone		= "Tel&#233;fono";
$shopper_form_fax		= "Fax";
$shopper_form_email		= "Correo Electr&#243;nico";

// Shopper Group List
$shopper_group_list_mnu		= "Listar Grupos de Clientes";
$shopper_group_list_lbl		= "Lista de Grupos de Clientes";
$shopper_group_list_name	= "Nombre del Grupo";
$shopper_group_list_description	= "Descripci&#243;n";


// Shopper Group Form
$shopper_group_form_lbl		= "Forma de Grupos de Clientes";
$shopper_group_form_mnu		= "A&#241;adir Grupos de Clientes";
$shopper_group_form_name	= "Nombre del Grupo";
$shopper_group_form_desc	= "Descripci&#243;n";
?>
