<?php
/*
 *
 * Copyright (c) Edikon Corporation.  All rights reserved.
 * Distributed under the phpShop Public License (pSPL) Version 1.0.
 *
 * $Id: ps_include.inc,v 1.1.1.1 2004/07/27 14:59:41 pablo Exp $
 *
 */

// Load Classes
require_once("shopper/lib/ps_shopper.inc");
require_once("shopper/lib/ps_shopper_group.inc");


// Instantiate Classes
$ps_shopper = new ps_shopper;
$ps_shopper_group = new ps_shopper_group;


?>
