<?php

# Some labels
$module[$modulename]["title"]   = "Tax Administration";
$module_menu            	= "$modulename/html/menu.ihtml";
$menu_label 			= "Tax Menu";

// User List
$tax_list_mnu			= "List Tax Rates";
$tax_list_lbl			= "Tax Rate List";
$tax_list_state  		= "Tax State or Region";
$tax_list_country  		= "Tax Country";
$tax_list_rate  		= "Tax Rate";

// User Form
$tax_form_mnu			= "Add Tax Rate";
$tax_form_lbl			= "Add Tax Information";
$tax_form_state			= "Tax State or Region";
$tax_form_country		= "Tax Country";
$tax_form_rate			= "Tax Rate";

?>
