<?php
/*
 *
    Copyright (C) Mike Wattier  <geek@devcompany.com>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * 
 *
 */

# Some labels
$module[$modulename]["title"]   = "Zone Shipping Administration";
$module_menu            	= MODROOT.$modulename."/html/menu.ihtml";
$menu_label 			= "Zone<br />Shipping<br />Menu";

$zone_list_mnu = "List Zones";
$zone_form_mnu = "Add Zone";
$zone_assign_mnu = "Assign Zones";


// assign zone List
$zone_assign_country_lbl = "Country";
$zone_assign_current_lbl = "Current Zone";
$zone_assign_assign_lbl = "Assign To Zone";
$zone_assign_update_lbl = "Update";
$assign_zone_pg_lbl = "Assign Zones";
// zone Form

$zone_form_name_lbl = "Zone Name";
$zone_form_desc_lbl = "Zone Description";
$zone_form_cost_per_lbl = "Zone Cost Per Item";
$zone_form_cost_limit_lbl = "Zone Cost Limit";

// List of zones
$zone_list_name_lbl = "Zone Name";
$zone_list_desc_lbl = "Zone Description";
$zone_list_cost_per_lbl = "Zone Cost Per Item";
$zone_list_cost_limit_lbl = "Zone Cost Limit";

?>
