<?php

# Some labels
$module[$modulename]["title"]   = "Administraci&#243;n de &#211;rdenes";
$module_menu            	= "$modulename/html/menu.ihtml";
$menu_label 			= "Men&#250; &#211;rdenes";

$order_status["P"]		= "Pendiente";
$order_status["C"]		= "Abrobado";
$order_status["X"]		= "Cancelado";

// Some menu options 
$order_confirm_mnu		= "Aprobar Orden";
$order_cancel_mnu		= "Cancelar Orden";
$order_print_mnu		= "Imprimir Orden";
$order_delete_mnu               = "Borrar Orden";

// Order List
$order_list_mnu			= "Listar &#211;rdenes";
$order_list_lbl			= "Lista de &#211;rdenes";
$order_list_id			= "N&#250;mero";
$order_list_cdate		= "Fecha";
$order_list_mdate		= "Modificado";
$order_list_status		= "Estatus";
$order_list_total		= "SubTotal";

// Order print
$order_print_po_lbl		= "Orden";
$order_print_po_number		= "N&#250;mero de Orden";
$order_print_po_date		= "Fecha de Orden";
$order_print_po_status		= "Estatus de Orden";
$order_print_cust_info_lbl	= "Informaci&#243;n del Cliente";
$order_print_bill_to_lbl	= "Direcci&#243;n de Cobro";
$order_print_ship_to_lbl	= "Direcci&#243;n de Envio";
$order_print_name		= "Nombre";
$order_print_company		= "Compa&#241;&#237;a";
$order_print_address_1		= "Dirrecci&#243;n 1";
$order_print_address_2		= "Dirrecci&#243;n 2";
$order_print_city		= "Ciudad";
$order_print_state		= "Estado";
$order_print_zip		= "C&#243;digo Postal";
$order_print_country		= "Pa&#237;s";
$order_print_phone		= "Tel&#233fono";
$order_print_fax		= "Fax";
$order_print_email		= "Email";
$order_print_items_lbl		= "Productos Ordernados";
$order_print_quantity		= "Cantidad";
$order_print_sku		= "SKU";
$order_print_price		= "Precio";
$order_print_total		= "Total";
$order_print_subtotal		= "SubTotal";
$order_print_total_tax		= "Total Impuestos";
$order_print_shipping		= "Envio";
$order_print_shipping_tax	= "Impuestos del Envio";
$order_print_payment_lbl	= "M&#233;todo de Pago";
$order_print_account_name	= "Nombre de la Cuenta";
$order_print_account_number	= "N&#250;mero de la Cuenta";
$order_print_expire_date	= "Fecha de Expiraci&#243;n";
$order_print_payment_log_lbl	= "Historial";


?>
