<?php

// User List
$user_list_mnu			= "List Users";
$user_list_lbl			= "User List";
$user_list_username		= "Username";
$user_list_full_name	= "Full Name";
$user_list_group		= "Group";

// User Form
$user_form_mnu			= "Add User";
$user_form_lbl			= "Add Information";
$user_form_billto_lbl		= "Bill To Information";
$user_form_shipto_lbl		= "Shipping Addresses";
$user_form_add_shipto_lbl	= "Add Address";
$user_form_address_label	= "Address Nickname";
$user_form_first_name		= "First Name";
$user_form_last_name		= "Last Name";
$user_form_middle_name		= "Middle Name";
$user_form_title		= "Title";
$user_form_username		= "Username";
$user_form_password_1		= "Password";
$user_form_password_2		= "Confirm Password";
$user_form_perms		= "Permissions";
$user_form_company_name		= "Company Name";
$user_form_address_1		= "Address 1";
$user_form_address_2		= "Address 2";
$user_form_city			= "City";
$user_form_state		= "State/Region";
$user_form_zip			= "Zip";
$user_form_country		= "Country";
$user_form_phone		= "Phone";
$user_form_fax			= "Fax";
$user_form_email		= "Email";

// Module List
$module_list_mnu		= "List Modules";
$module_list_lbl		= "Module List";
$module_list_name		= "Module Name";
$module_list_perms		= "Module Perms";
$module_list_functions		= "Functions";
$module_list_order		= "ListOrder";

// Module Form
$module_form_mnu		= "Add Module";
$module_form_lbl		= "Module Information";
$module_form_name		= "Module Name";
$module_form_perms		= "Module Perms";
$module_form_header		= "Module Header";
$module_form_footer		= "Module Footer";
$module_form_menu		= "Module Menu?";
$module_form_order		= "Display Order";
$module_form_description	= "Module Description";
$module_form_language_code	= "Language Code";
$module_form_language_file	= "Language File";

// Function List
$function_list_mnu		= "List Functions";
$function_list_lbl		= "Function List";
$function_list_name 		= "Function Name";
$function_list_class 		= "Class Name";
$function_list_method 		= "Class Method";
$function_list_perms 		= "Perms";

// Module Form
$function_form_mnu		= "Add Function";
$function_form_lbl		= "Function Information";
$function_form_name		= "Function Name";
$function_form_class		= "Class Name";
$function_form_method		= "Class Method";
$function_form_perms		= "Function Perms";
$function_form_description	= "Function Description";

?>
