<?php

# Some labels
$module[$modulename]["menu"]	= "Order";
$module[$modulename]["title"]   = "Order Administration";
$module_menu            	= "$modulename/html/menu.ihtml";
$menu_label 			= "Order Menu";

$order_status["P"]		= "Pending";
$order_status["C"]		= "Completed";
$order_status["X"]		= "Cancelled";

// Some menu options 
$order_confirm_mnu		= "Confirm Order";
$order_cancel_mnu		= "Cancel Order";
$order_print_mnu		= "Print Order";
$order_delete_mnu		= "Delete Order";

// Order List
$order_list_mnu			= "List Orders";
$order_list_lbl			= "Order List";
$order_list_id			= "Order Number";
$order_list_cdate		= "Order Date";
$order_list_mdate		= "Last Modified";
$order_list_status		= "Status";
$order_list_total		= "SubTotal";

// Order print
$order_print_po_lbl		= "Purchase Order";
$order_print_po_number		= "Order Number";
$order_print_po_date		= "Order Date";
$order_print_po_status		= "Order Status";
$order_print_cust_info_lbl	= "Customer Information";
$order_print_bill_to_lbl	= "Bill To";
$order_print_ship_to_lbl	= "Ship To";
$order_print_name		= "Name";
$order_print_company		= "Company";
$order_print_address_1		= "Address 1";
$order_print_address_2		= "Address 2";
$order_print_city		= "City";
$order_print_state		= "State/Region";
$order_print_zip		= "Zip";
$order_print_country		= "Country";
$order_print_phone		= "Phone";
$order_print_fax		= "Fax";
$order_print_email		= "Email";
$order_print_items_lbl		= "Order Items";
$order_print_quantity		= "Quantity";
$order_print_sku		= "SKU";
$order_print_price		= "Price";
$order_print_total		= "Total";
$order_print_subtotal		= "SubTotal";
$order_print_total_tax		= "Tax Total";
$order_print_shipping		= "Shipping";
$order_print_shipping_tax	= "Shipping Tax";
$order_print_payment_lbl	= "Payment Method";
$order_print_account_name	= "Account Name";
$order_print_account_number	= "Account Number";
$order_print_expire_date	= "Expire Date";
$order_print_payment_log_lbl	= "Payment Log";
$order_print_shipping_lbl       = "Shipping Information";
$order_print_shipping_carrier_lbl   = "Carrier";
$order_print_shipping_mode_lbl      = "Shipping Mode";
$order_print_shipping_date_lbl      = "Ship Date";
$order_print_shipping_price_lbl      = "Shipping Price";

$order_status_list_mnu		= "List Order Status Types";
$order_status_form_mnu		= "Add Order Status Type";

$order_status_list_code         = "Order Status Code";
$order_status_list_name         = "Order Status Name";

$order_status_form_lbl		= "Order Status";
$order_status_form_code	        = "Order Status Code";
$order_status_form_name		= "Order Status Name";
$order_status_form_list_order	= "List Order";

?>
