<?php

# Some labels
$module[$modulename]["title"]   	= "Product Administration";
$module_menu            		= "$modulename/html/menu.ihtml";
$menu_label 				= "Product Menu";

$product_current_lbl			= "Current Product";
$item_current_lbl			= "Current Item";

// Product Inventory
$product_inventory_lbl			= "Product Inventory";
$product_inventory_mnu			= "View Inventory";
$product_inventory_price			= "Price";
$product_inventory_stock			= "Number";
$product_inventory_weight			= "Weight";
// Product List
$product_list_mnu			= "List Products";
$product_list_lbl			= "Product List";
$product_list_name			= "Product Name";
$product_list_sku			= "SKU";
$product_list_category       = "Category";
$product_list_publish			= "Publish";

// Product Form
$product_form_mnu			= "Add Product";
$product_form_add_item_mnu              = "Add Item";
$product_form_add_another_item_mnu      = "Add Another Item";

$product_form_new_product_lbl           = "New Product";
$product_form_update_product_lbl        = "Update Product";
$product_form_product_info_lbl          = "Product Information";
$product_form_product_status_lbl        = "Product Status";
$product_form_product_dim_weight_lbl    = "Product Dimensions and Weight";
$product_form_product_images_lbl        = "Product Images";

$product_form_new_item_lbl              = "New Item";
$product_form_update_item_lbl           = "Update Item";
$product_form_item_info_lbl             = "Item Information";
$product_form_item_status_lbl           = "Item Status";
$product_form_item_dim_weight_lbl       = "Item Dimensions and Weight";
$product_form_item_images_lbl           = "Item Images";
$product_form_return_lbl 		= "Return to Parent Product";
$product_form_image_delete_lbl		= "Type \"none\" to delete current image.";
$product_form_product_items_lbl         = "Product Items";
$product_form_item_attributes_lbl       = "Item Attributes";
$product_form_delete_product_msg        = "Are you sure you want to delete this Product\\nand the Items related to it?";
$product_form_delete_item_msg           = "Are you sure you want to delete this Item?";
$product_form_vendor			= "Vendor";
$product_form_sku			= "SKU";
$product_form_name			= "Name";
$product_form_url			= "URL";
$product_form_category			= "Category";
$product_form_price			= "Retail Price";
$product_form_description		= "Flypage Description";
$product_form_s_desc			= "Short Description";
$product_form_in_stock			= "In Stock";
$product_form_on_order			= "On Order";
$product_form_available_date		= "Availability Date";
$product_form_special			= "On Special";
$product_form_discount_type		= "Discount Type";
$product_form_publish			= "Publish?";
$product_form_length			= "Length";
$product_form_width			= "Width";
$product_form_height			= "Height";
$product_form_dimension_uom		= "Unit of Measure";
$product_form_weight			= "Weight";
$product_form_weight_uom		= "Unit of Measure";
$product_form_thumb_image		= "Thumb Nail";
$product_form_full_image		= "Full Image";

// Product Display
$product_display_add_product_lbl        = "Product Add Results";
$product_display_update_product_lbl     = "Product Update Results";
$product_display_add_item_lbl           = "Item Add Results";
$product_display_update_item_lbl        = "Item Update Results";

// Product Category List
$category_list_mnu			= "List Categories";
$category_list_lbl			= "Category Tree";

// Product Category Form
$category_form_mnu			= "Add Category";
$category_form_lbl			= "Category Information";
$category_form_name			= "Category Name";
$category_form_parent			= "Parent";
$category_form_description		= "Category Description";
$category_form_publish			= "Publish?";
$category_form_flypage			= "Category Flypage";

// Product Attribute List
$attribute_list_mnu			= "List Attributes";
$attribute_list_lbl			= "Attribute List for";
$attribute_list_name			= "Attribute Name";
$attribute_list_order			= "List Order";

// Product Attribute Form
$attribute_form_mnu			= "Add Attribute";
$attribute_form_lbl			= "Attribute Form";
$attribute_form_new_for_product         = "New Attribute for Product";
$attribute_form_update_for_product      = "Update Attribute for Product";
$attribute_form_new_for_item            = "New Attribute for Item";
$attribute_form_update_for_item         = "Update Attribute for Item";
$attribute_form_name			= "Attribute Name";
$attribute_form_order			= "List Order";

// Product Price List
$price_list_mnu				= "List Categories";
$price_list_lbl				= "Price Tree";
$price_list_for_lbl			= "Price for";
$price_list_group_name			= "Group Name";
$price_list_price			= "Price";
$product_list_currency			= "Currency";

// Product Price Form
$price_form_mnu				= "Add Price";
$price_form_lbl				= "Price Information";
$price_form_new_for_product             = "New Price for Product";
$price_form_update_for_product          = "Update Price for Product";
$price_form_new_for_item                = "New Price for Item";
$price_form_update_for_item             = "Update Price for Item";
$price_form_price			= "Price";
$price_form_currency			= "Currency";
$price_form_group			= "Shopper Group";
$price_publish				= "Publish?";
?>
