<?php

# Some labels
$home_title 		= "Home";
$cart_title 		= "Cart";
$checkout_title 	= "Checkout";
$login_title 		= "Login";
$logout_title 		= "Logout";
$browse_title		= "Browse";
$search_title 		= "Search";
$account_title 		= "Account<br />Maintenance";
$navigation_title	= "Navigation";
$department_title	= "Department";

$module_topmenu            = "$modulename/html/topmenu.ihtml";
$module_leftmenu            = "$modulename/html/leftmenu.ihtml";

$browse_lbl             = "Browse";
$search_lbl             = "Search";
$flypage_lbl            = "Product Details";

$product_name_title     = "Product Name";
$product_category_title = "Product Category";
$product_thumb_title 	= "Thumbnail Image";
$product_price_title 	= "Price";
$product_desc_title     = "Product Description";
$order_status =array();
$order_status["P"]["label"]= "Pending";
$order_status["C"]["label"]= "Confirmed";
$order_status["X"]["label"]= "Canceled";

$cart_name              = "Name";
$cart_sku               = "SKU";
$cart_price             = "Price";
$cart_quantity          = "Quantity";
$cart_subtotal          = "Subtotal";

# Some messages
$empty_cart             = "Your cart is currently empty.";
$price_label            = "Price: $";
$order_button_label     = "Order";

?>
