<?php

# Some labels
$module[$modulename]["title"]   = "Shopper Administration";
$module_menu            	= "$modulename/html/menu.ihtml";
$menu_label 			= "Shopper Menu";


// Shopper List
$shopper_list_mnu		= "List Shoppers";
$shopper_list_lbl		= "Shopper List";
$shopper_list_username		= "User Name";
$shopper_list_name		= "Full Name";
$shopper_list_group		= "Group";

// Shopper Form
$shopper_form_mnu		= "Add Shopper";
$shopper_form_lbl		= "Shopper Information";
$shopper_form_billto_lbl	= "Bill To Information";
$shopper_form_address_info_lbl	= "Information";
$shopper_form_shipto_lbl	= "Shipping Information";
$shopper_form_add_shipto_lbl	= "Add Address";
$shopper_form_address_label	= "Address Nickname";
$shopper_form_username		= "User Name";
$shopper_form_first_name	= "First Name";
$shopper_form_last_name		= "Last Name";
$shopper_form_middle_name	= "Middle Name";
$shopper_form_title		= "Title";
$shopper_form_shoppername	= "Shoppername";
$shopper_form_password_1	= "Password";
$shopper_form_password_2	= "Confirm Password";
$shopper_form_group		= "Shopper Group";
$shopper_form_company_name	= "Company Name";
$shopper_form_address_1		= "Address 1";
$shopper_form_address_2		= "Address 2";
$shopper_form_city		= "City";
$shopper_form_state		= "State/Region";
$shopper_form_zip		= "Zip";
$shopper_form_country		= "Country";
$shopper_form_phone		= "Phone";
$shopper_form_fax		= "Fax";
$shopper_form_email		= "Email";

// Shopper Group List
$shopper_group_list_mnu		= "List Shopper Groups";
$shopper_group_list_lbl		= "Shopper Group List";
$shopper_group_list_name	= "Group Name";
$shopper_group_list_description	= "Group Description";


// Shopper Group Form
$shopper_group_form_lbl		= "Shopper Group Form";
$shopper_group_form_mnu		= "Add Shopper Group";
$shopper_group_form_name	= "Group Name";
$shopper_group_form_desc	= "Group Description";
?>


