<?php
/*
 *
 * Copyright (c) uli (uli@ulisoft.com  All rights reserved.
 * Distributed under the phpShop Public License (pSPL) Version 1.0.
 *
 *
 */

// Load Classes
require_once("topic/lib/ps_topic.inc");
require_once("topic/lib/ps_topic_status.inc");
require_once("topic/lib/ps_topic_group.inc");

// Instantiate Classes

$ps_topic = new ps_topic;
$ps_topic_status = new ps_topic_status;
$ps_topic_group = new ps_topic_group;

?>


