<?php

# Some labels
$home_title 		= "Home";
$cart_title 		= "Carrito";
$checkout_title 	= "Checkout";
$login_title 		= "Login";
$logout_title 		= "Logout";
$browse_title		= "Browse";
$search_title 		= "Buscar";
$account_title 		= "Su Cuenta";
$navigation_title	= "Navegacion";
$department_title	= "Departamento";

$module_topmenu            = "$modulename/html/topmenu.ihtml";
$module_leftmenu            = "$modulename/html/leftmenu.ihtml";

$browse_lbl		= "Ojear";
$search_lbl		= "Busqueda";
$flypage_lbl		= "Detalles del Producto";

$product_name_title     = "Nobre del Producto";
$product_category_title = "Categoria";
$product_thumb_title 	= "Imagen del Thumbnail";
$product_price_title    = "Precio";
$product_desc_title     = "Descripcion";
$order_status =array();
$order_status["P"]["label"]= "Ordenado";
$order_status["C"]["label"]= "Confirmado";
$order_status["X"]["label"]= "Cancelado";

$cart_name              = "Nombre";
$cart_sku               = "SKU";
$cart_price             = "Precio";
$cart_quantity          = "Cantidad";
$cart_subtotal          = "Subtotal";

# Some messages
$empty_cart             = "Su carrito esta vacio.";
$price_label            = "Precio: $";
$order_button_label     = "Ordenar";

?>
